-- MySQL Script generated by MySQL Workbench
-- Mon May 10 18:07:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdcontrole
-- -----------------------------------------------------
-- 
-- Base de dados

-- -----------------------------------------------------
-- Schema bdcontrole
--
-- 
-- Base de dados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdcontrole` DEFAULT CHARACTER SET utf8 ;
USE `bdcontrole` ;

-- -----------------------------------------------------
-- Table `bdcontrole`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontrole`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(100) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `fone` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

select * from pessoafisica;
insert into pessoafisica values('22222222', 'victor');

-- -----------------------------------------------------
-- Table `bdcontrole`.`PessoaFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontrole`.`PessoaFisica` (
  `idPessoaFisica` INT NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_PessoaFisica_Cliente1_idx` (`idPessoaFisica` ASC) VISIBLE,
  PRIMARY KEY (`idPessoaFisica`),
  CONSTRAINT `fk_PessoaFisica_Cliente1`
    FOREIGN KEY (`idPessoaFisica`)
    REFERENCES `bdcontrole`.`Cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontrole`.`PessoaJuridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontrole`.`PessoaJuridica` (
  `idPessoaJuridica` INT NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `nomeFantasia` VARCHAR(50) NOT NULL,
  `razaoSocial` VARCHAR(50) NOT NULL,
  INDEX `fk_PessoaJuridica_Cliente1_idx` (`idPessoaJuridica` ASC) VISIBLE,
  PRIMARY KEY (`idPessoaJuridica`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaJuridica_Cliente1`
    FOREIGN KEY (`idPessoaJuridica`)
    REFERENCES `bdcontrole`.`Cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

select * from PessoaJuridica;
select * from PessoaFisica;
select * from cliente;
-- -----------------------------------------------------
-- Table `bdcontrole`.`Colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontrole`.`Colaborador` (
  `idColaborador` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `dataAdmissao` DATE NOT NULL,
  `dataDesligamento` DATE NULL,
  PRIMARY KEY (`idColaborador`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontrole`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontrole`.`Projeto` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `idCliente` INT NOT NULL,
  `idLider` INT NOT NULL,
  `matricula` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `escopo` VARCHAR(20) NOT NULL,
  `dataInicio` DATE NOT NULL,
  `dataPrevConclusao` DATE NULL,
  `dataConclusao` DATE NULL,
  PRIMARY KEY (`idProjeto`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  INDEX `fk_Projeto_Colaborador1_idx` (`idLider` ASC) VISIBLE,
  INDEX `fk_Projeto_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_Colaborador1`
    FOREIGN KEY (`idLider`)
    REFERENCES `bdcontrole`.`Colaborador` (`idColaborador`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projeto_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bdcontrole`.`Cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontrole`.`Alocacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontrole`.`Alocacao` (
  `idAlocacao` INT NOT NULL AUTO_INCREMENT,
  `idProjeto` INT NOT NULL,
  `idColaborador` INT NOT NULL,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NULL,
  `horasSemana` DECIMAL(6,1) NULL,
  `valorHora` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`idAlocacao`),
  INDEX `fk_Projeto_has_Colaborador_Colaborador1_idx` (`idColaborador` ASC) VISIBLE,
  INDEX `fk_Alocacao_Projeto1_idx` (`idProjeto` ASC) VISIBLE,
  CONSTRAINT `fk_Projeto_has_Colaborador_Colaborador1`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `bdcontrole`.`Colaborador` (`idColaborador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alocacao_Projeto1`
    FOREIGN KEY (`idProjeto`)
    REFERENCES `bdcontrole`.`Projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdcontrole`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdcontrole`.`Tarefa` (
  `idTarefa` INT NOT NULL AUTO_INCREMENT,
  `idColaborador` INT NOT NULL,
  `idProjeto` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NULL,
  `status` VARCHAR(10) NOT NULL,
  `previsaoHoras` DECIMAL(6,1) NOT NULL,
  `qtdHoras` DECIMAL(6,1) NULL,
  PRIMARY KEY (`idTarefa`),
  INDEX `fk_Colaborador_has_Projeto_Projeto1_idx` (`idProjeto` ASC) VISIBLE,
  INDEX `fk_Colaborador_has_Projeto_Colaborador1_idx` (`idColaborador` ASC) VISIBLE,
  CONSTRAINT `fk_Colaborador_has_Projeto_Colaborador1`
    FOREIGN KEY (`idColaborador`)
    REFERENCES `bdcontrole`.`Colaborador` (`idColaborador`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Colaborador_has_Projeto_Projeto1`
    FOREIGN KEY (`idProjeto`)
    REFERENCES `bdcontrole`.`Projeto` (`idProjeto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from colaborador;